// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/Nulandmori/micorservices-pattern/services/item/ent/item"
	"github.com/Nulandmori/micorservices-pattern/services/item/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescPrice is the schema descriptor for price field.
	itemDescPrice := itemFields[3].Descriptor()
	// item.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	item.PriceValidator = itemDescPrice.Validators[0].(func(int64) error)
	// itemDescID is the schema descriptor for id field.
	itemDescID := itemFields[0].Descriptor()
	// item.DefaultID holds the default value on creation for the id field.
	item.DefaultID = itemDescID.Default.(func() uuid.UUID)
}
